

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/waffle?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: jsangmin
    password: shn06124
  jpa:
    hibernate:
      ddl-auto: update # ??? ??? ??? ??? ??
    show-sql: true # mysql debug mode, ?? ??? ??? ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate: # custom options
        format_sql: true # sql ??? ????? ???


